### PR TITLE
Support for custom components as notificationBody

### PR DESCRIPTION
**Pull request by die20**
Hey!

I needed a way to add a custom component as the notification body - this method allows for you to use a custom component, it will not use the default notification body if a customComponent is found. 

Just thought it'd be a good addition :)

Thanks

### CODE REVIEW

**Comment by robcalcroft** [comment]
Hey! Thanks for the PR. I'm a bit confused on what this PR adds. Isn't the point of notification body that it already supports a custom component to be used for the Notification?

**Comment by die20** [comment]
Oh, maybe it does - I didn't pick up on that from the docs. How would I pass in a custom component to the plugin? 

When I say a custom component, I mean one that is formatted and styled on its own. Not just changing the title, text, icon, onPress parts of the notification.

**Comment by robcalcroft** [comment]
Yeah you can just add your custom component using the `notificationBodyComponent` prop

**Comment by robcalcroft** [comment]
Closing this due to inactivity

**Pull request closed without merging**
